### ISSUE TITLE
Compatibility with ResearchGate?

### ISSUE THREAD

**Issue by sc-pan** [trilliaapp/zoterouploader#1]
Hi -- I got this app in hopes that it would simplify the process of uploading PDFs from ResearchGate, which contains thousands of author-provided PDF full text articles.  Zotero browser add-ins/plug-ins can easily do that.

However, multiple attempts to enter a ResearchGate URL, either the article page or the PDF URL itself, generates an error in Zotero Uploader ("....is not reachable (429)").  Is there a way to fix this?

Example URLs:

ARTICLE PAGE with link to free PDF:
https://www.researchgate.net/publication/264988491_The_Effect_of_Testing_Versus_Restudy_on_Retention_A_Meta-Analytic_Review_of_the_Testing_Effect

PDF Direct Link:
https://www.researchgate.net/profile/Christopher-Rowland-2/publication/264988491_The_Effect_of_Testing_Versus_Restudy_on_Retention_A_Meta-Analytic_Review_of_the_Testing_Effect/links/56bb82d808ae2481ab6ac4ba/The-Effect-of-Testing-Versus-Restudy-on-Retention-A-Meta-Analytic-Review-of-the-Testing-Effect.pdf?_sg%5B0%5D=PCdP2XR99KMyHW8DLeKG-rnSeloj-E5cZH8ABsfEpQBY2N2L9C_GWUIQfx1lOE1fEayLxsPe875LDvZyWi5qZw.gRbh33a9E8hD8wb7s4-_LoH9YUB0HWbdIo0r_rRGxxtlo4mhkEGC10GU-3vQ4Ib7pd4nKtYF8a5c95sMXpzn6g&_sg%5B1%5D=efmzsObJz18wTDBWBsYYanZcxeMIn8TOCR-C3Kcz6yKla7vw9MFL__PBZvxnMdNPh9YJGXVyvpYFAmpbg7ArSfGUBCzCuoKgW8yqlrjFZgHP.gRbh33a9E8hD8wb7s4-_LoH9YUB0HWbdIo0r_rRGxxtlo4mhkEGC10GU-3vQ4Ib7pd4nKtYF8a5c95sMXpzn6g&_iepl=

**Comment by trilliaapp** [comment]
Hi sc-pan,

Thank you for reporting this issue.

Error 429 (https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/429) means that too many requests were made to the ResearchGate servers in a short timespan (this is typically linked to your IP). The links you provide here work well for me.

Can you let me know if they still do not work?

**Comment by sc-pan** [comment]
Thanks.  I tried with 1 ResearchGate URL this morning and it worked.  However, I just tried it again with a second URL and it's giving the same 429 error.  This is just my second request of the day and no one else uses this IP address.  Is there a way to fix this?  It kind of defeats the purpose if one can only upload 1 article every 24 hrs.  Thanks for any help.

**Comment by trilliaapp** [comment]
Thank you.

That is surprising and should certainly be fixed. I will try to reproduce
this on my side.

Can you add a few links and let me know at which frequency you are making
these requests?

**Comment by sc-pan** [comment]
Thanks for the help!  I made two requests earlier today.  An initial request for the main page, which uploaded the data from the paper but not the PDF, and then a second request with the URL for the PDF itself, which successfully uploaded the PDF.   This was one of the successfully used URLs:

https://www.researchgate.net/publication/348006788_Supporting_the_self-regulated_use_of_retrieval_practice_A_higher_education_classroom_experiment?_iepl%5BgeneralViewId%5D=e0cIF77K18QXe3LE5H7gmoHyQpj1FPDBh0Sl&_iepl%5Bcontexts%5D%5B0%5D=searchReact&_iepl%5BviewId%5D=6LeoKV4vt4MVOa3UO1YMm81Y3LQBBQykJNfb&_iepl%5BsearchType%5D=publication&_iepl%5Bdata%5D%5BcountLessEqual20%5D=1&_iepl%5Bdata%5D%5BinteractedWithPosition1%5D=1&_iepl%5Bdata%5D%5BwithoutEnrichment%5D=1&_iepl%5Bposition%5D=1&_iepl%5BrgKey%5D=PB%3A348006788&_iepl%5BtargetEntityId%5D=PB%3A348006788&_iepl%5BinteractionType%5D=publicationTitle

No further requests were made until just a short while ago, when I attempted to upload the URL for the following PDF, and failing that, the data from the paper itself.   Both yielded the 429 error.  The URLs are:

https://www.researchgate.net/publication/355177302_Transferring_the_sandwich_principle_to_instructional_videos_is_it_worth_the_effort?_iepl%5BgeneralViewId%5D=J0YZDLkoPFqKHZkAibBe7gCmCz1eONL7Mcg1&_iepl%5Bcontexts%5D%5B0%5D=searchReact&_iepl%5BviewId%5D=014d08I857AheTisFneYX2zLJnI91nH2jeew&_iepl%5BsearchType%5D=publication&_iepl%5Bdata%5D%5BcountLessEqual20%5D=1&_iepl%5Bdata%5D%5BinteractedWithPosition1%5D=1&_iepl%5Bdata%5D%5BwithoutEnrichment%5D=1&_iepl%5Bposition%5D=1&_iepl%5BrgKey%5D=PB%3A355177302&_iepl%5BtargetEntityId%5D=PB%3A355177302&_iepl%5BinteractionType%5D=publicationTitle

https://www.researchgate.net/journal/BMC-Medical-Education-1472-6920/publication/355177302_Transferring_the_sandwich_principle_to_instructional_videos_is_it_worth_the_effort/links/61651fb71eb5da761e8372ee/Transferring-the-sandwich-principle-to-instructional-videos-is-it-worth-the-effort.pdf?_sg%5B0%5D=GnaXMR265BnPSsuvaH23DZ0w-_jdyka1_6iT5S27TRscv2iHgG0gJ-m_YdXlMxjbPuQmdrB8Jt0BNpSZ02Z4TA.EtiDY0qc6T5fWOPUnvA_NY9701ffXvyRET8dkfMHhntBTR9nigMR_MCGQFT5GC9UOBJaQiRdXrq7lG-MnW0rQg&_sg%5B1%5D=24pXZUJY8b8OUu1x9PObngZm4WU4artc6PoOv6xEllaiQ0bY7U1qfocARhTM_sXQJ_HCAjO2zAxebMtTZsEJp8QkMAAcoM_hs7MQrVfTiE3C.EtiDY0qc6T5fWOPUnvA_NY9701ffXvyRET8dkfMHhntBTR9nigMR_MCGQFT5GC9UOBJaQiRdXrq7lG-MnW0rQg&_sg%5B2%5D=QbjPLQPemtAjlfwisxHE5Sq9B9k_A9ufQbCqRDBbdWQT5_ogSQUr5rDg89vFbHQ9cBjt1yBp9FaDVZA.4hgW3xk_GsJTv3XDlOsWFrdX-TlFvFPFK-sfai9i6vODF5TPPhdfJMgRWKg_p9-FfUxGhStR6phsdt2d-AP-SQ&_iepl%5BgeneralViewId%5D=J0YZDLkoPFqKHZkAibBe7gCmCz1eONL7Mcg1&_iepl%5Bcontexts%5D%5B0%5D=searchReact&_iepl%5BviewId%5D=014d08I857AheTisFneYX2zLJnI91nH2jeew&_iepl%5BsearchType%5D=publication&_iepl%5Bdata%5D%5BcountLessEqual20%5D=1&_iepl%5Bdata%5D%5BinteractedWithPosition1%5D=1&_iepl%5Bdata%5D%5BwithoutEnrichment%5D=1&_iepl%5Bposition%5D=1&_iepl%5BrgKey%5D=PB%3A355177302&_iepl%5BtargetEntityId%5D=PB%3A355177302&_iepl%5BinteractionType%5D=publicationDownload

**Comment by trilliaapp** [comment]
Unfortunately, I could not reproduce the issue on my side (despite issuing
more than 10 queries in a row during about 1 minute).

Since the app does not seem to be working for you (or your particular
use-case seems to affect how the app retrieves articles from ResearchGate)
and if you bought the app recently (less than 14 days I believe), you
should probably ask for a refund from Apple.
I can happily add you to our list of beta testers (thereby getting
app updates early and for free and in exchange for bug reports).

Can you confirm that you can access the links provided from Safari on your
phone? (right after they fail in the app).
If so, can you try sharing the ReseachGate page with the app (using the
share icon) and let me know if that works?

Thank you

**Comment by sc-pan** [comment]
Thanks for being so responsive.  I confirm that the links were provided from Safari.  

To update: I have reproduced the error multiple times today, but found a workaround.  The 429 error appears when I am connected to a Wi-Fi network.  When I turn off the Wi-Fi on the phone, and rely on cellular data, then all the links that I tried work.

For now, that seems to be an effective solution.  I do think the app is very useful, as it saves me from having to go to my computer and re-input all the PDF/article links that I have found on my phone, and then port to Zotero.  And now that a workaround so far seems to work, things are better.  I understand that the app will continue to be updated, which is great.

Thanks again.

**Comment by trilliaapp** [comment]
Thank you for your update.

It may be that multiple people are using the same Wi-Fi network and use
ResearchGate frequently (or go through the same proxy). I find it
interesting that Safari seems to be able to avoid this issue (I'll try to
investigate this and understand why this is the case).
In any case, the next update should be better at detecting the PDF file
from the abstract page on ResearchGate (so hopefully that simplifies your
workflow).

**Comment by trilliaapp** [comment]
The new version (1.7) should work better with ResearchGate (e.g., it should retrieve the PDF even if the URL points to the abstract page). It should be available shortly.
